### ISSUE TITLE
Dated User Interface

### ISSUE THREAD

**Issue by isaiahdaviscom** [Tpessia/devtools-notes#1]
Are there plans to update the interface?

I am wondering if I can contribute to this project?

**Comment by Tpessia** [comment]
Hi @isaiahdaviscom!!

Really sorry for the delayed response, but contributions are totally welcome!

I've been thinking about some UX improvements, like allowing vertical resize of the textareas and creating a tab system to allow for better organization/categorization of the notes.

Do you have some improvements in mind?

**Comment by isaiahdaviscom** [comment]
Those are some of the same UX improvements that I had in mind. I love the extension find it especially useful some of my personal projects. I am new to contributing and also looking for a side project to be involved in.
